version: 2
jobs:
  build:
    docker:
      - image: turbinelabs/build-common:0.9.19.9
        cmd: ["/bin/bash"]

    working_directory: "/go/src/github.com/turbinelabs/tbnctl"

    environment:
      - PROJECT: github.com/turbinelabs/tbnctl
      - TEST_RUNNER_OUTPUT: /tmp/test-results/testrunner
      - TBN_CI_BUILD: 1

    steps:
      - checkout

      - run: env | sort

      - run:
          name: install deps
          command: go get $PROJECT/...

      - run:
          name: install testrunner
          command: |
            go get github.com/turbinelabs/test/testrunner
            go install github.com/turbinelabs/test/testrunner

      - run:
          name: run tests
          command: bash code_coverage.sh $(go list $PROJECT/... | grep -v /vendor/)

      - run:
          name: upload code coverage
          command: |
            if curl --silent --fail https://codecov.io/bash >codecov.sh; then
              bash <codecov.sh
            else
              echo skipping codecov -- script download error
              cat codecov.sh
            fi

      - store_test_results:
          path: /tmp/test-results
